HTMLArea.classesLabels = {"align-left":"Linksb\u00fcndig","align-center":"Zentrieren","align-right":"Rechtsb\u00fcndig","csc-frame-frame1":"Rahmen mit grauen Hintergrund","csc-frame-frame2":"Rahmen mit gelbem Hintergrund","important":"Wichtig","name-of-person":"Name der Person","detail":"Detail","component-items":"Komponenten","action-items":"Befehle","component-items-ordered":"Komponenten","action-items-ordered":"Befehle"};
HTMLArea.classesValues = {"align-left":"text-align: left;","align-center":"text-align: center;","align-right":"text-align: right;","csc-frame-frame1":"background-color: #EDEBF1; border: 1px solid #333333;","csc-frame-frame2":"background-color: #F5FFAA; border: 1px solid #333333;","important":"color: #8A0020;","name-of-person":"color: #10007B;","detail":"color: #186900;","component-items":"color: #186900;","action-items":"color: #8A0020;","component-items-ordered":"color: #186900;","action-items-ordered":"color: #8A0020;"};
HTMLArea.classesNoShow = {};
HTMLArea.classesAlternating = {};
HTMLArea.classesCounting = {};
HTMLArea.classesSelectable = {};
HTMLArea.classesRequires = {};
HTMLArea.classesRequiredBy = {};
HTMLArea.classesXOR = {};
