<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3training"
 *
 * Auto generated by Extension Builder 2016-01-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3-Training',
	'description' => 'Unsere erste Template-Extension',
	'category' => 'templates',
	'author' => 'Wolfgang Wagner',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
